language: rust
rust:
  - stable
  - beta
  - nightly
notifications:
  email:
    - caden@cadendepatie.com
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev
before_script:
  - rustc --version
  - cargo --version
branches:
  only:
    - master
matrix:
  allow_failures:
    - rust: nightly